2014-08-26 01:23:13 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /cakephp/app/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AppController), Object(CakeRequest))
#2 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-26 01:29:44 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /cakephp/app/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AppController), Object(CakeRequest))
#2 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-26 01:30:24 Error: [MissingActionException] Action AppController::View() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'View',
)
Request URL: /cakephp/app/View/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AppController), Object(CakeRequest))
#2 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-26 01:30:31 Error: [MissingActionException] Action AppController::View() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'View',
)
Request URL: /cakephp/app/View/Atletas/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AppController), Object(CakeRequest))
#2 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-26 01:30:37 Error: [MissingActionException] Action AppController::View() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'View',
)
Request URL: /cakephp/app/View/Atletas/
Stack Trace:
#0 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AppController), Object(CakeRequest))
#2 C:\xampp\htdocs\cakephp\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-29 21:44:02 Error: [MissingActionException] Action AppController::index() could not be found.
Exception Attributes: array (
  'controller' => 'AppController',
  'action' => 'index',
)
Request URL: /fidelity/app/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(AppController), Object(CakeRequest))
#2 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-29 21:57:19 Error: [MissingActionException] Action ClientesController::index() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'index',
)
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest))
#2 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-08-30 20:20:12 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:20:12 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:20:52 Error: Fatal Error (4): syntax error, unexpected '=' in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 11]
2014-08-30 20:20:52 Error: [FatalErrorException] syntax error, unexpected '='
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:21:11 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:21:11 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:21:58 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:21:58 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:22:21 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:22:21 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:23:49 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:23:49 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:27:35 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:27:35 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:28:33 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:28:33 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:29:40 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:29:40 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:30:00 Error: Fatal Error (4): syntax error, unexpected 'endforeach' (T_ENDFOREACH) in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 15]
2014-08-30 20:30:00 Error: [FatalErrorException] syntax error, unexpected 'endforeach' (T_ENDFOREACH)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 15, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:45:29 Error: [MissingControllerException] Controller class FornecedoresController could not be found.
Exception Attributes: array (
  'class' => 'FornecedoresController',
  'plugin' => NULL,
)
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-30 20:46:03 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 20:46:03 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:47:15 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 20:47:15 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:47:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 20:47:32 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:48:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 20:48:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:50:14 Error: [MissingControllerException] Controller class FornecedorsController could not be found.
Exception Attributes: array (
  'class' => 'FornecedorsController',
  'plugin' => NULL,
)
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-30 20:52:26 Error: [MissingControllerException] Controller class FornecedorsController could not be found.
Exception Attributes: array (
  'class' => 'FornecedorsController',
  'plugin' => NULL,
)
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-30 20:52:31 Error: [MissingControllerException] Controller class FornecedorsController could not be found.
Exception Attributes: array (
  'class' => 'FornecedorsController',
  'plugin' => NULL,
)
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-30 20:54:25 Error: [MissingControllerException] Controller class FornecedorsController could not be found.
Exception Attributes: array (
  'class' => 'FornecedorsController',
  'plugin' => NULL,
)
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-30 20:54:42 Error: [MissingControllerException] Controller class FornecedorsController could not be found.
Exception Attributes: array (
  'class' => 'FornecedorsController',
  'plugin' => NULL,
)
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-30 20:56:08 Error: [MissingControllerException] Controller class FornecedorsController could not be found.
Exception Attributes: array (
  'class' => 'FornecedorsController',
  'plugin' => NULL,
)
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-08-30 20:56:32 Error: Fatal Error (1): Call to a member function save() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedorsController.php, line 14]
2014-08-30 20:56:32 Error: [FatalErrorException] Call to a member function save() on a non-object
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 14, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:57:06 Error: [MissingTableException] Table fornecedors for model Fornecedor was not found in datasource default.
Exception Attributes: array (
  'table' => 'fornecedors',
  'class' => 'Fornecedor',
  'ds' => 'default',
)
Request URL: /fidelity/fornecedors/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Model\Model.php(3525): Model->setSource('fornecedors')
#1 C:\xampp\htdocs\fidelity\lib\Cake\Model\Model.php(1759): Model->getDataSource()
#2 C:\xampp\htdocs\fidelity\app\Controller\FornecedorsController.php(14): Model->save(Array)
#3 [internal function]: FornecedorsController->cadastrar()
#4 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(FornecedorsController), Array)
#5 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#6 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(FornecedorsController), Object(CakeRequest))
#7 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
2014-08-30 20:58:21 Error: [MissingViewException] View file "C:\xampp\htdocs\fidelity\app\View\Fornecedors\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\fidelity\\app\\View\\Fornecedors\\index.ctp',
)
Request URL: /fidelity/fornecedors/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(FornecedorsController), Object(CakeRequest))
#4 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-30 20:58:36 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 20:58:36 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 20:58:45 Error: [MissingViewException] View file "C:\xampp\htdocs\fidelity\app\View\Fornecedors\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\fidelity\\app\\View\\Fornecedors\\index.ctp',
)
Request URL: /fidelity/fornecedors
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(FornecedorsController), Object(CakeRequest))
#4 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-30 20:59:22 Error: [MissingViewException] View file "C:\xampp\htdocs\fidelity\app\View\Fornecedors\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'C:\\xampp\\htdocs\\fidelity\\app\\View\\Fornecedors\\index.ctp',
)
Request URL: /fidelity/fornecedors
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(468): View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#3 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(FornecedorsController), Object(CakeRequest))
#4 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2014-08-30 21:25:26 Error: Fatal Error (4): syntax error, unexpected '$name' (T_VARIABLE), expecting function (T_FUNCTION) in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 6]
2014-08-30 21:25:26 Error: [FatalErrorException] syntax error, unexpected '$name' (T_VARIABLE), expecting function (T_FUNCTION)
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 6)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 6, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 6, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:25:45 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:25:45 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:33:20 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:33:20 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:33:23 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:33:23 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:34:21 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:34:21 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:34:22 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:34:22 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:34:50 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:34:50 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:35:14 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:35:14 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:48:04 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:48:04 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 21:48:28 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 7]
2014-08-30 21:48:28 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 7, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:47:18 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:47:18 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:47:41 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:47:41 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:47:43 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:47:43 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:49:35 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:49:35 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:56:48 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:56:48 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:56:50 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:56:50 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:56:52 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:56:52 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:57:30 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:57:30 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:57:32 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:57:32 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 22:59:25 Error: Fatal Error (1): Call to a member function find() on a non-object in [C:\xampp\htdocs\fidelity\app\Controller\FornecedoresController.php, line 8]
2014-08-30 22:59:25 Error: [FatalErrorException] Call to a member function find() on a non-object
Request URL: /fidelity/fornecedores
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-08-30 23:05:04 Error: [MissingTableException] Table fornecedors for model Fornecedor was not found in datasource default.
Exception Attributes: array (
  'table' => 'fornecedors',
  'class' => 'Fornecedor',
  'ds' => 'default',
)
Request URL: /fidelity/fornecedors
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Model\Model.php(3525): Model->setSource('fornecedors')
#1 C:\xampp\htdocs\fidelity\lib\Cake\Model\Model.php(2921): Model->getDataSource()
#2 C:\xampp\htdocs\fidelity\lib\Cake\Model\Model.php(2893): Model->_readDataSource('all', Array)
#3 C:\xampp\htdocs\fidelity\app\Controller\FornecedorsController.php(10): Model->find('all')
#4 [internal function]: FornecedorsController->index()
#5 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(FornecedorsController), Array)
#6 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#7 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(FornecedorsController), Object(CakeRequest))
#8 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2014-08-30 23:07:22 Error: [MissingActionException] Action FornecedorsController::adicionar() could not be found.
Exception Attributes: array (
  'controller' => 'FornecedorsController',
  'action' => 'adicionar',
)
Request URL: /fidelity/fornecedors/adicionar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(FornecedorsController), Object(CakeRequest))
#2 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-09-01 23:09:06 Error: [MissingActionException] Action ClientesController::visualizar() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'visualizar',
)
Request URL: /fidelity/clientes/visualizar/3992
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest))
#2 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-09-01 23:34:30 Error: Fatal Error (4): syntax error, unexpected 'endif' (T_ENDIF) in [C:\xampp\htdocs\fidelity\app\View\Pages\home.ctp, line 58]
2014-09-01 23:34:30 Error: [FatalErrorException] syntax error, unexpected 'endif' (T_ENDIF)
Request URL: /fidelity/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 58, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 58, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-02 00:48:56 Error: [MissingActionException] Action ClientesController::fidelity() could not be found.
Exception Attributes: array (
  'controller' => 'ClientesController',
  'action' => 'fidelity',
)
Request URL: /fidelity/clientes/fidelity/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest))
#2 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-09-02 00:49:16 Error: [MissingControllerException] Controller class FidelityController could not be found.
Exception Attributes: array (
  'class' => 'FidelityController',
  'plugin' => NULL,
)
Request URL: /fidelity/fidelity/cadastrar
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-02 23:54:30 Error: Fatal Error (4): syntax error, unexpected '.', expecting ')' in [C:\xampp\htdocs\fidelity\app\Controller\ClientesController.php, line 5]
2014-09-02 23:54:30 Error: [FatalErrorException] syntax error, unexpected '.', expecting ')'
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 5)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 5, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 5, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-02 23:59:59 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(886): HelperCollection->load('Javascript', Array)
#1 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(354): View->loadHelpers()
#2 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(1241): View->__construct(Object(ClientesController))
#3 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(940): Controller->_getViewObject()
#4 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#5 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest))
#6 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-09-03 00:03:38 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-03 00:03:38 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-03 00:04:37 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-03 00:04:37 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 20:31:52 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-05 20:31:53 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 20:48:08 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-05 20:48:08 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 20:58:15 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-05 20:58:15 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 21:21:12 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-05 21:21:12 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 21:23:03 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-05 21:23:03 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 21:23:49 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-05 21:23:49 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 21:26:56 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 48]
2014-09-05 21:26:56 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 48, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 21:32:04 Error: Fatal Error (1): Call to a member function codeBlock() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 50]
2014-09-05 21:32:04 Error: [FatalErrorException] Call to a member function codeBlock() on a non-object
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 21:32:20 Error: Fatal Error (1): Call to undefined method View::codeBlock() in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 50]
2014-09-05 21:32:20 Error: [FatalErrorException] Call to undefined method View::codeBlock()
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 50, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to undefin...', 'C:\\xampp\\htdocs...', 50, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-05 22:11:33 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Javascript')
#1 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(837): HelperCollection->__isset('Javascript')
#2 C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp(50): View->__get('Javascript')
#3 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(948): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(910): View->_evaluate('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(471): View->_render('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#8 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest))
#9 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-09-05 22:13:49 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Javascript')
#1 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(837): HelperCollection->__isset('Javascript')
#2 C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp(50): View->__get('Javascript')
#3 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(948): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(910): View->_evaluate('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(471): View->_render('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#8 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest))
#9 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-09-05 22:14:52 Error: [MissingHelperException] Helper class JavascriptHelper could not be found.
Exception Attributes: array (
  'class' => 'JavascriptHelper',
  'plugin' => false,
)
Request URL: /fidelity/clientes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\View\HelperCollection.php(63): HelperCollection->load('Javascript')
#1 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(837): HelperCollection->__isset('Javascript')
#2 C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp(50): View->__get('Javascript')
#3 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(948): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(910): View->_evaluate('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\fidelity\lib\Cake\View\View.php(471): View->_render('C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(954): View->render(NULL, NULL)
#7 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#8 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ClientesController), Object(CakeRequest))
#9 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2014-09-06 21:02:30 Error: [MissingControllerException] Controller class ProfissoesController could not be found.
Exception Attributes: array (
  'class' => 'ProfissoesController',
  'plugin' => NULL,
)
Request URL: /fidelity/profissoes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-06 21:03:14 Error: [MissingControllerException] Controller class ProfissoesController could not be found.
Exception Attributes: array (
  'class' => 'ProfissoesController',
  'plugin' => NULL,
)
Request URL: /fidelity/profissoes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-06 22:02:57 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 50]
2014-09-06 22:02:57 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes/index/page:2
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-06 22:04:03 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 50]
2014-09-06 22:04:03 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes/index/page:2
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-06 22:04:05 Error: Fatal Error (1): Call to a member function link() on a non-object in [C:\xampp\htdocs\fidelity\app\View\Clientes\index.ctp, line 50]
2014-09-06 22:04:05 Error: [FatalErrorException] Call to a member function link() on a non-object
Request URL: /fidelity/clientes/index/page:2
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#2 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 50, Array)
#3 C:\xampp\htdocs\fidelity\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-09-06 22:29:06 Error: [MissingControllerException] Controller class ProfissoesController could not be found.
Exception Attributes: array (
  'class' => 'ProfissoesController',
  'plugin' => NULL,
)
Request URL: /fidelity/profissoes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-09-06 22:30:19 Error: [MissingModelException] Cliente
Request URL: /fidelity/profissoes/
Stack Trace:
#0 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(1080): PaginatorComponent->paginate('Cliente', Array, Array)
#1 C:\xampp\htdocs\fidelity\app\Controller\ProfissoesController.php(11): Controller->paginate('Cliente')
#2 [internal function]: ProfissoesController->index()
#3 C:\xampp\htdocs\fidelity\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(ProfissoesController), Array)
#4 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#5 C:\xampp\htdocs\fidelity\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(ProfissoesController), Object(CakeRequest))
#6 C:\xampp\htdocs\fidelity\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
